# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SaveASGeojson
                                 A QGIS plugin
 This plugin saves spatial data as geojson data format
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-14
        copyright            : (C) 2022 by brenda chepngetich
        email                : brendabre18@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SaveASGeojson class from file SaveASGeojson.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .save_as_geojson import SaveASGeojson
    return SaveASGeojson(iface)
